spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book
    username: mydb
    password: a123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  server:
    servlet:
      session:
        persistent: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 21616981503-emrgmqs1ua042gq3aa1g6evhaabk1uac.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE